---
title: Developer's log
timezone: Europe/Warsaw
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
name: Michał Łapacz
avatar: "/theme/img/avatar.png"
twitter_username: wapacz
github_username: wapacz
email: michal.lapacz@gmail.com
description: I work on many projects in many languages, so I decided to store my experiences
  in these areas.
baseurl: 
include:
- _pages
- _portfolio
sass:
  sass_dir: theme/_sass
  style: compressed
url: 
theme: minima
plugins:
- jekyll-feed
