---
title: Developer's log
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: michal.lapacz@gmail.com
description: I work on many projects in many languages, so I decided to store my experiences
  in these areas.
baseurl: 
url: 
twitter_username: wapacz
github_username: wapacz
theme: minima
plugins:
- jekyll-feed
