---
title: Fat T-shape
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Michał Łapacz
description: I work on many projects in many languages, so I decided to store my experiences.
permalink: "/:title/"
lang: en
excerpt_separator: |2+



date_format: "%B %d, %Y"
sidebar: true
show_excerpts: false
show_related: true
show_description: true
show_title: true
dark_header: true
minimal: false
navigation:
- file: index.html
  icon: home
- file: README.md
  icon: address-card
external:
- title: Github
  icon: github
  url: https://github.com/wapacz
comments: 
plugins:
- jekyll-feed
