---
title: Developer's log

timezone: Europe/Warsaw
name: Michał Łapacz
avatar: /theme/img/avatar.png   # Path to an avatar image
twitter_username: wapacz
github_username: wapacz
email: michal.lapacz@gmail.com
description: I work on many projects in many languages, so I decided to store my experiences

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl:

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages", "_portfolio"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the projects into a collection.
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: michal.lapacz@gmail.com
description: I work on many projects in many languages, so I decided to store my experiences
  in these areas.
baseurl: 
url: 
twitter_username: wapacz
github_username: wapacz
theme: minima
plugins:
- jekyll-feed
